CREATE DATABASE IF NOT EXISTS cows;
USE cows;
CREATE TABLE IF NOT EXISTS cowList(
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR (50) NOT NULL,
    description VARCHAR (250) NOT NULL,
    PRIMARY KEY (id)
);